name: Continuous Delivery

on:
  workflow_dispatch:
  push:
  release:
    types: [published]

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nmslib_metabrainz-wheels-${{ runner.os }}
          path: wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build python_bindings --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: nmslib_metabrainz-sdist
          path: python_bindings/dist/*.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    environment:
      name: pypi
      url: https://pypi.org/p/nmslib-metabrainz
    permissions:
      id-token: write  # required for PyPI upload
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: nmslib_metabrainz-*
          path: dist/
          merge-multiple: true
      - name: Prepare distributions
        run: |
          ls -l dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')

